apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/application: {{ .Release.Namespace }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/application: {{ .Release.Namespace }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/application: {{ .Release.Namespace }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: ticker
          image: {{ printf "%s:%s" .Values.image.name .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          resources: {{- toYaml .Values.resources | nindent 12}}

      restartPolicy: Always
